num1 = int(input("Enter Number1: "))
num2 = int(input("Enter Number2: "))
print("--------------------")
print(num1,"+",num2,"=",num1+num2)
print(num1,"-",num2,"=",num1-num2)
print(num1,"*",num2,"=",num1*num2)
print(num1,"/",num2,"=",num1/num2)